jobs:
  build:
    name: ${{ matrix.pretty_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" ${{ matrix.build_args }}
        -f "dockerfiles/${{ matrix.dockerfile }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" -e DOCKERFILE="${{ matrix.dockerfile
        }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.8.19
          product: ansible
          version: 2.8.19
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.9.19
          product: ansible
          version: 2.9.19
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.8.20rc1
          product: ansible
          version: 2.8.20rc1
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.9.20rc1
          product: ansible
          version: 2.9.20rc1
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.10.7
          product: ansible-base
          version: 2.10.7
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.10.8rc1
          product: ansible-base
          version: 2.10.8rc1
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.11.0b4
          product: ansible-core
          version: 2.11.0b4
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
    timeout-minutes: 20
  macos-build:
    name: ${{ matrix.pretty_name }}
    runs-on: ${{ matrix.dockerfile }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - env:
        DOCKERFILE: ${{ matrix.dockerfile }}
        PPA: ${{ matrix.ppa }}
        PRE: ${{ matrix.pre }}
        PRODUCT: ${{ matrix.product }}
        VERSION: ${{ matrix.version }}
      name: Run tests
      run: bash entrypoint.sh
    strategy:
      fail-fast: false
      matrix:
        include: []
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
  pull_request: null
  push: null
  schedule:
  - cron: 0 13 * * *

