jobs:
  build:
    name: ${{ matrix.dockerfile }}, ${{ matrix.pre }}, ${{ matrix.product }}, ${{
      matrix.version }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" ${{ matrix.build_args }}
        -f "dockerfiles/${{ matrix.dockerfile }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" -e DOCKERFILE="${{ matrix.dockerfile
        }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos7
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos7
          pre: rpm
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: centos8
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubi7
          pre: rpm
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubi7
          pre: rpm
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.8.18
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.8.19rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          product: ansible-core
          version: 2.11.0b1
        - PPA: ansible/ansible-2.8
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.8.18
        - PPA: ansible/ansible-2.9
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.17
        - PPA: ansible/ansible-2.10
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.5
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible
          version: 2.9.17
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-base
          version: 2.10.5
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          product: ansible-core
          version: 2.11.0b1
    timeout-minutes: 20
  macos-build:
    name: ${{ matrix.dockerfile }}, ${{ matrix.pre }}, ${{ matrix.product }}, ${{
      matrix.version }}
    runs-on: ${{ matrix.dockerfile }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - env:
        DOCKERFILE: ${{ matrix.dockerfile }}
        PPA: ${{ matrix.ppa }}
        PRE: ${{ matrix.pre }}
        PRODUCT: ${{ matrix.product }}
        VERSION: ${{ matrix.version }}
      name: Run tests
      run: bash entrypoint.sh
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          product: ansible-core
          version: 2.11.0b1
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          product: ansible
          version: 2.9.17
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          product: ansible
          version: 2.9.18rc1
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          product: ansible-base
          version: 2.10.5
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          product: ansible-base
          version: 2.10.6rc1
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          product: ansible-core
          version: 2.11.0b1
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
  pull_request: null
  push: null
  schedule:
  - cron: 0 0 * * *

